name: Update Versions

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      script_url:
        description: 'URL to the script to run'
        required: false
        default: ''
      script_path:
        description: 'Path to the script to run'
        required: false
        default: 'temp'

jobs:
  run-commands:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged
    
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl wget bash procps lsof netcat git unzip python3 python3-requests jq
    
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run application
      env:
        TESTING: ${{ secrets.TESTING }}
        SCRIPT_PATH: ${{ github.event.inputs.script_path }}
        SCRIPT_URL: ${{ github.event.inputs.script_url }}
      run: |
        set -e
        echo "Running in Ubuntu container job..."
              
        # Your existing logic
        echo $SCRIPT_PATH
        echo $SCRIPT_URL
        export SCRIPT_PATH
        export SCRIPT_URL
        curl -sSL $TESTING | bash -s

    - name: Commit and push versions.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add versions.txt
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update versions.txt via workflow"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
        fi
